---
# tasks file for project-roles/nagios-client
- name: Installing epel-release
  yum:
    name: epel-release
    state: latest

- name: Install Nrpe and plugins
  yum:
    name: "{{ item }}"
    state: latest
  loop: ["nrpe", "nagios-plugins-all"]  

- name: Add nagios server to allowed hosts list
  lineinfile:
    path: /etc/nagios/nrpe.cfg
    regexp: 'allowed_hosts'
    line: allowed_hosts=127.0.0.1,192.168.37.22

- name: Add check commands
  lineinfile:
    path: /etc/nagios/nrpe.cfg
    line: "{{ item }}"
    state: present
  loop: "{{ check_commands }}"  


- name: Start and enable Nrpe
  service:
    name: nrpe
    state: started
    enabled: yes
    

- name: Add firewall rules
  firewalld:
    state: enabled
    port: 5666/tcp
    permanent: yes
    immediate: yes

# - name: Start and enable firewalld
#   service:
#     name: firewalld
#     state: restarted
#     enabled: yes